nameOverride: ""

fullnameOverride: ""

replicaCount: 1

image:
  repository: dradoaica/aspnetcore.ignite-server
  tag: "2.16"
  pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  create: true
  name: ""

env:
  DEFAULT_ON_HEAP_MEMORY: "2048"
  DEFAULT_OFF_HEAP_MEMORY: "4096"
  USE_TCP_DISCOVERY_STATIC_IP_FINDER: "false"
  ENABLE_AUTHENTICATION: "true"
  IGNITE_USER_PASSWORD: "ignite"
  USE_SSL: "true"
  SSL_KEY_STORE_FILE_PATH: "config/server.jks"
  SSL_KEY_STORE_PASSWORD: "123456"
  SSL_TRUST_STORE_FILE_PATH: "config/trust.jks"
  SSL_TRUST_STORE_PASSWORD: "123456"
  USE_CLIENT_SSL: "true"
  SSL_CLIENT_CERTIFICATE_PATH: "config/thin-client-cert.pfx"
  SSL_CLIENT_CERTIFICATE_PASSWORD: "123456"
  METRICS_EXPIRE_TIME_IN_HOURS: "24"
  METRICS_LOG_FREQUENCY_IN_MINUTES: "5"
  METRICS_UPDATE_FREQUENCY_IN_SECONDS: "60"
  ENABLE_OFF_HEAP_METRICS: "false"

## envFrom can be used to pass configmaps or secrets as environment
#envFrom:
#   - configMapRef:
#       name: env-configmap
#   - secretRef:
#       name: env-secrets

## Additional init containers to run before the pods. For example, be used to run a sidecar that chown Logs storage.
extraInitContainers: [ ]
#  - name: volume-mount-hack
#    image: busybox
#    command: ["sh", "-c", "chown -R 1000:1000 logs"]

## Additional containers to run alongside the pods. For example, be used to run jmx-exporter.
extraContainers: [ ]
#  - name: jmxexporter
#    image: sscaling/jmx-prometheus-exporter
#    command: ["sh", "-c", "chown -R 1000:1000 logs"]

persistence:
  workVolume:
    size: 8Gi

## extraVolumes and extraVolumeMounts allows you to mount other volumes
## Example Use Cases:
##  mount certificates to enable tls
#extraVolumes:
# - name: ignite-keystore
#   secret:
#     defaultMode: 288
#     secretName: ignite-keystore
# - name: ignite-truststore
#   secret:
#     defaultMode: 288
#     secretName: ignite-truststore
#extraVolumeMounts:
# - name: ignite-keystore
#   mountPath: /certs/keystore
#   readOnly: true
# - name: ignite-truststore
#   mountPath: /certs/truststore
#   readOnly: true

resources:
  requests:
    cpu: 300m
    memory: 2Gi
  limits:
    cpu: 2
    memory: 9Gi

nodeSelector: { }

tolerations: [ ]

affinity: { }

priorityClassName: ""
